<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KatalonDesktop</name>
   <tag></tag>
   <elementGuidId>9c44176f-fdfd-46ba-b095-8ae1ea0856a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.Repo_name_y4kf6o.u-flex.u-flexAlignItemsBaseline > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div/ul/li/div/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;KatalonDesktop&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>551119d1-c917-47d7-ba4b-52cac949ae37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://github.com/katalonstudio/KatalonDesktop</value>
      <webElementGuid>532ab619-0955-4af8-9e0f-ac1fd48b0599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KatalonDesktop</value>
      <webElementGuid>2c67f7cd-5143-41ef-958f-9ee01ea0f910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;DefaultLayout_1jug6qr u-flex u-flexCol&quot;]/div[@class=&quot;u-flexGrow1&quot;]/div[@class=&quot;Container_16pg94n&quot;]/div[@class=&quot;Container_inner_w9z6jj-o_O-Container_padding_1cv73u5&quot;]/div[@class=&quot;Profile_container_9yvb3b&quot;]/div[@class=&quot;Profile_content_rci9mp Grid Grid--withGutter&quot;]/div[@class=&quot;Profile_repos_koa90h Grid-cell u-sm-size1of2&quot;]/ul[1]/li[@class=&quot;ItemList_item_dgdnyv&quot;]/div[1]/p[@class=&quot;Repo_name_y4kf6o u-flex u-flexAlignItemsBaseline&quot;]/a[1]</value>
      <webElementGuid>03736e20-fc07-45c5-98e4-ccc51fd998c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div/ul/li/div/p/a</value>
      <webElementGuid>2afd5f7a-5318-4572-bb83-2c373d97081d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'KatalonDesktop')]</value>
      <webElementGuid>18fd1a3c-a423-426e-b50c-7602c6692e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repositories'])[1]/following::a[1]</value>
      <webElementGuid>0a801089-1377-4f71-8950-89492a9e7143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@katalonstudio'])[1]/following::a[1]</value>
      <webElementGuid>4384e766-e079-4645-ae52-b8af8f5ccb8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Followers'])[2]/preceding::a[1]</value>
      <webElementGuid>db7a054f-f010-4f11-9a40-614ae6f2f0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='source on GitHub'])[1]/preceding::a[1]</value>
      <webElementGuid>cc3aef54-7821-4849-aaeb-9a35d37ca3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KatalonDesktop']/parent::*</value>
      <webElementGuid>18389155-6ee3-4560-9cc2-60b2ad6882ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://github.com/katalonstudio/KatalonDesktop')]</value>
      <webElementGuid>0c5016b1-9a69-4675-a49c-b3aa13e927a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/p/a</value>
      <webElementGuid>13e8813c-7449-4831-af3c-56008eba9c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://github.com/katalonstudio/KatalonDesktop' and (text() = 'KatalonDesktop' or . = 'KatalonDesktop')]</value>
      <webElementGuid>159aa877-c19f-4933-bd4c-69ecae822735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
