<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_build</name>
   <tag></tag>
   <elementGuidId>ee22ac75-a7fd-47c3-acb9-52df75107003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.react-directory-row-name-cell-large-screen > div.react-directory-filename-column > div.overflow-hidden > div.react-directory-filename-cell > div.react-directory-truncate > a.Link--primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='folder-row-0']/td[2]/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;build, (Directory)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c7cfff3-cc05-4349-8972-3e63a6f87be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>build</value>
      <webElementGuid>5dc417b7-3fb9-496d-bad4-34d23a82848b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>build, (Directory)</value>
      <webElementGuid>eb113231-1c9d-46e5-b5cc-825b28bd6e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Link--primary</value>
      <webElementGuid>18830aaf-39bf-488e-be41-f1f56fb76596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/PrasadG193/external-snapshot-metadata/tree/main/build</value>
      <webElementGuid>741bd3d3-8291-44ea-8021-5bd8f9871cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>build</value>
      <webElementGuid>1c1a685d-25ac-4114-91ef-53fdff4b9db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;folder-row-0&quot;)/td[@class=&quot;react-directory-row-name-cell-large-screen&quot;]/div[@class=&quot;react-directory-filename-column&quot;]/div[@class=&quot;overflow-hidden&quot;]/div[@class=&quot;react-directory-filename-cell&quot;]/div[@class=&quot;react-directory-truncate&quot;]/a[@class=&quot;Link--primary&quot;]</value>
      <webElementGuid>9f15e39b-9a9d-4e9d-ab5f-3186a0a7a348</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='folder-row-0']/td[2]/div/div/div/div/a</value>
      <webElementGuid>4b77a386-5ee4-4a5a-ab7b-918fc2980dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'build')])[2]</value>
      <webElementGuid>597bfcd1-da1c-4d9d-908e-d0dd3ed61229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='build'])[1]/following::a[1]</value>
      <webElementGuid>0fe7e590-62f8-47ed-bcad-96b00b25033b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/following::a[4]</value>
      <webElementGuid>baeda5ca-5795-472e-9532-452035c5e7bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add grpc server and client implementation'])[1]/preceding::a[1]</value>
      <webElementGuid>bf0c0008-13c2-4cb9-9823-3d65783af6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aug 8, 2023'])[1]/preceding::a[2]</value>
      <webElementGuid>c9ccca86-9154-48a4-95c6-c2ca98bb566a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/PrasadG193/external-snapshot-metadata/tree/main/build')])[2]</value>
      <webElementGuid>d2d32421-b5e3-47b8-b14f-c71ad3720635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/a</value>
      <webElementGuid>b3b67a4b-b20a-4dc3-a01a-ee9db2c7c812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'build' and @href = '/PrasadG193/external-snapshot-metadata/tree/main/build' and (text() = 'build' or . = 'build')]</value>
      <webElementGuid>b5bdc2c2-dd1b-4c48-bb7c-5cee6d2d3b5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
