<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Drivers</name>
   <tag></tag>
   <elementGuidId>665fa557-f9d4-4874-bb0a-3eaa4cce2d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#folder-row-2 > td.react-directory-row-name-cell-large-screen > div.react-directory-filename-column > div.overflow-hidden > div.react-directory-filename-cell > div.react-directory-truncate > a.Link--primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='folder-row-2']/td[2]/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Drivers, (Directory)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0021cc31-403d-4f76-8c3d-66eade3a3f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Drivers</value>
      <webElementGuid>994d603b-1555-4d8e-b0d7-8b1204b5250e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Drivers, (Directory)</value>
      <webElementGuid>aa44757f-f4bf-4c4b-97f7-33400002a284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Link--primary</value>
      <webElementGuid>5c0684f4-6543-4c3d-ae9c-612671bc540c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Sanchita19200/KatalonTrainingProject/tree/main/Drivers</value>
      <webElementGuid>8bee6414-0f7a-4566-9ad9-e2c9172a93a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drivers</value>
      <webElementGuid>745af9a1-cc0b-4ad2-9d62-92f2f175fe73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;folder-row-2&quot;)/td[@class=&quot;react-directory-row-name-cell-large-screen&quot;]/div[@class=&quot;react-directory-filename-column&quot;]/div[@class=&quot;overflow-hidden&quot;]/div[@class=&quot;react-directory-filename-cell&quot;]/div[@class=&quot;react-directory-truncate&quot;]/a[@class=&quot;Link--primary&quot;]</value>
      <webElementGuid>cd22f445-2727-4fa6-aade-37f464b1d580</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='folder-row-2']/td[2]/div/div/div/div/a</value>
      <webElementGuid>9fe8eccd-16a7-4dd0-8c97-1493a552dc68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Drivers')])[2]</value>
      <webElementGuid>43e02429-d68a-4776-8385-7c749186477b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drivers'])[1]/following::a[1]</value>
      <webElementGuid>6bab54f9-c844-44dd-bf5c-5234c2004434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jul 30, 2024'])[2]/following::a[2]</value>
      <webElementGuid>ea8c8349-a08f-43da-8b6b-fc4d5ca2615e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[3]/preceding::a[1]</value>
      <webElementGuid>ad4d5821-579c-449b-81e5-93ec7b14ed6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jul 30, 2024'])[3]/preceding::a[2]</value>
      <webElementGuid>abd56695-2677-4234-8b95-63e26231f721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/Sanchita19200/KatalonTrainingProject/tree/main/Drivers')])[2]</value>
      <webElementGuid>aa3f1f4c-05fa-4cfa-aff7-a9ff4bed0f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/div/div/div/a</value>
      <webElementGuid>4904427b-9607-4b10-90b5-a6b11be8d5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Drivers' and @href = '/Sanchita19200/KatalonTrainingProject/tree/main/Drivers' and (text() = 'Drivers' or . = 'Drivers')]</value>
      <webElementGuid>b2c864aa-c0b5-4b33-ac9b-39907ba275bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
