<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drivers</name>
   <tag></tag>
   <elementGuidId>3ba16b92-65fb-4614-91de-2bab95ad9619</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#folder-row-2 > td.react-directory-row-name-cell-large-screen > div.react-directory-filename-column</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='folder-row-2']/td[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Drivers, (Directory)&quot;i] >> div >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7545d772-ea40-45d8-99ff-34253d250486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-directory-filename-column</value>
      <webElementGuid>df377425-94b4-4664-9798-410beaedf2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drivers</value>
      <webElementGuid>b9bf010b-c562-4385-9e98-e119d515ad93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;folder-row-2&quot;)/td[@class=&quot;react-directory-row-name-cell-large-screen&quot;]/div[@class=&quot;react-directory-filename-column&quot;]</value>
      <webElementGuid>ebfe7ca0-06af-4bdb-93b7-1d2dc75dc619</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='folder-row-2']/td[2]/div</value>
      <webElementGuid>0879b58e-31cc-4627-9fea-bc6b915aa89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drivers'])[1]/following::div[1]</value>
      <webElementGuid>edad732e-9609-4452-aa58-0113e78cfa64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jul 30, 2024'])[2]/following::div[5]</value>
      <webElementGuid>b5a16289-26de-4b40-b097-1a0d3274f5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[3]/preceding::div[4]</value>
      <webElementGuid>34ebfb12-a10d-4a11-89f3-1afc8d4d106b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div</value>
      <webElementGuid>da314189-f78b-435e-9b83-fb4427bac54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Drivers' or . = 'Drivers')]</value>
      <webElementGuid>aa02b322-969d-440b-b8ab-88a9f7eee1d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
