<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_jrohitofficial</name>
   <tag></tag>
   <elementGuidId>befc1f09-e224-46f0-b209-05c9a3d7c343</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/ul/li[2]/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;jrohitofficial's avatar jrohitofficial&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>036cc853-b0fb-4296-bb63-cefa5bd61d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>User_username_rnfkwd</value>
      <webElementGuid>f6d5e5b6-e8b8-4085-bcc3-4079a63f3c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>jrohitofficial</value>
      <webElementGuid>b19e3c77-6257-4a68-9335-088fb148cb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;DefaultLayout_1jug6qr u-flex u-flexCol&quot;]/div[@class=&quot;u-flexGrow1&quot;]/div[@class=&quot;Container_16pg94n&quot;]/div[@class=&quot;Container_inner_w9z6jj-o_O-Container_padding_1cv73u5&quot;]/div[@class=&quot;SearchResultsContainer_item_1mcype0&quot;]/ul[@class=&quot;SearchResults_1uxrx9c u-sm-flex u-sm-flexWrap&quot;]/li[@class=&quot;SearchResults_item_1mclqe7&quot;]/a[@class=&quot;User_abw475 u-flex&quot;]/p[@class=&quot;User_username_rnfkwd&quot;]</value>
      <webElementGuid>d8730497-535f-4b70-8bd9-056ca61980f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/ul/li[2]/a/p</value>
      <webElementGuid>e3c86218-4fac-4603-b275-1fb2db1d9168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rohit'])[1]/following::p[2]</value>
      <webElementGuid>29987210-6fa6-48ad-b8c2-f69e56441054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::p[3]</value>
      <webElementGuid>f2f4b0c8-e715-4652-bb0d-b2b47886dc18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::p[41]</value>
      <webElementGuid>254f3b8c-1334-4a1c-83b1-33f6379d5bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='source on GitHub'])[1]/preceding::p[41]</value>
      <webElementGuid>7785cce3-45fe-4172-b125-ca01a6360744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='jrohitofficial']/parent::*</value>
      <webElementGuid>99bcc8f9-1f5b-412f-89eb-fb8081492fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/p</value>
      <webElementGuid>a70ce2c8-7e0d-4785-ab26-265d4144febe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'jrohitofficial' or . = 'jrohitofficial')]</value>
      <webElementGuid>36506447-1aeb-49bb-8d3f-ffbdc7beba6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
