<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nisha Pathak_Avatar_1pcpsid u-imgResponsive</name>
   <tag></tag>
   <elementGuidId>69ef517f-5b27-452e-9059-e0f0fae09c6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.Avatar_1pcpsid.u-imgResponsive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/ul/li/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Nishant-Pathak's avatar Nishant-Pathak&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7bde262a-18fd-4d9b-b8fb-f1c2c1639c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Nishant-Pathak's avatar</value>
      <webElementGuid>f9540b3f-5684-4601-bf40-74f8cc3aeb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Avatar_1pcpsid u-imgResponsive</value>
      <webElementGuid>6f9a922e-e59e-4e9b-abc2-5fa7b927b938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://avatars.githubusercontent.com/u/724049?v=4&amp;s=180</value>
      <webElementGuid>32bfcc74-69d0-454e-90ab-b13dbaa1cd34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>0fd484d6-ad7d-4a40-9e57-ca0e08872c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;DefaultLayout_1jug6qr u-flex u-flexCol&quot;]/div[@class=&quot;u-flexGrow1&quot;]/div[@class=&quot;Container_16pg94n&quot;]/div[@class=&quot;Container_inner_w9z6jj-o_O-Container_padding_1cv73u5&quot;]/div[@class=&quot;SearchResultsContainer_item_1mcype0&quot;]/ul[@class=&quot;SearchResults_1uxrx9c u-sm-flex u-sm-flexWrap&quot;]/li[@class=&quot;SearchResults_item_1mclqe7&quot;]/a[@class=&quot;User_abw475 u-flex&quot;]/div[@class=&quot;User_wrapAvatar_3afm6b&quot;]/div[@class=&quot;Image_e296pg&quot;]/img[@class=&quot;Avatar_1pcpsid u-imgResponsive&quot;]</value>
      <webElementGuid>445cb7e1-378b-44e4-b2ed-f5b3c4ef8c94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/ul/li/a/div/div/img</value>
      <webElementGuid>1b4941ee-3175-4d05-87d0-22a1e83239de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=&quot;Nishant-Pathak's avatar&quot;]</value>
      <webElementGuid>013a3c6f-40e0-46ac-a7f0-1809ea8cf29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>dcd0aa74-8830-41bf-bb7e-77ec9fc46d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = concat(&quot;Nishant-Pathak&quot; , &quot;'&quot; , &quot;s avatar&quot;) and @src = 'https://avatars.githubusercontent.com/u/724049?v=4&amp;s=180']</value>
      <webElementGuid>deaff6fc-6b8f-4d10-98ec-c99b01a0a727</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
