<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ntresvalles1</name>
   <tag></tag>
   <elementGuidId>a114bc75-6853-4d24-b56a-d16384f41476</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.url.fn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='repository-container-header']/div/div/div/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ntresvalles1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8465294f-59cd-4546-880d-2061a5fcebb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>url fn</value>
      <webElementGuid>18ea3cbb-91f9-4880-8011-dfaee09fd23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>author</value>
      <webElementGuid>40680988-6f31-49a4-8e88-12c5c0770f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovercard-type</name>
      <type>Main</type>
      <value>user</value>
      <webElementGuid>8e6c9b7b-3098-484c-9ab4-0e9ff83f5d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hovercard-url</name>
      <type>Main</type>
      <value>/users/ntresvalles1/hovercard</value>
      <webElementGuid>1349c6d3-637e-4bfe-9f94-934f89febc60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-octo-click</name>
      <type>Main</type>
      <value>hovercard-link-click</value>
      <webElementGuid>d0e366da-ddae-43cf-893f-454a77d8ea75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-octo-dimensions</name>
      <type>Main</type>
      <value>link_type:self</value>
      <webElementGuid>3c683e59-7bbb-48f3-bb7c-077a90deb40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ntresvalles1</value>
      <webElementGuid>ae850c83-7ed0-4a27-9b2e-993058c369b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        ntresvalles1
</value>
      <webElementGuid>16ca7069-66f2-4887-9742-dca2888613eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repository-container-header&quot;)/div[@class=&quot;d-flex flex-nowrap flex-justify-end mb-3  px-3 px-lg-5&quot;]/div[@class=&quot;flex-auto min-width-0 width-fit&quot;]/div[@class=&quot;d-flex flex-wrap flex-items-center wb-break-word f3 text-normal&quot;]/span[@class=&quot;author flex-self-stretch&quot;]/a[@class=&quot;url fn&quot;]</value>
      <webElementGuid>8318bfc5-aba5-41a3-b74a-0ea0903bdd9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repository-container-header']/div/div/div/span/a</value>
      <webElementGuid>e67a884b-5c60-4f89-a1b5-6919b609812b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ntresvalles1')]</value>
      <webElementGuid>9b6b442c-f200-4fc9-9c6b-3f274b302350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reload'])[3]/following::a[1]</value>
      <webElementGuid>fa6b52c9-24b1-45e2-815b-dcdb8add9264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::a[1]</value>
      <webElementGuid>626edd9e-d28b-45d3-834b-e78f9d221dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[1]/preceding::a[2]</value>
      <webElementGuid>0f7c50ee-9e89-4ca0-98b8-36e7b87b5c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ntresvalles1']/parent::*</value>
      <webElementGuid>a884b177-ee0b-4f24-a85a-e143359e8d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ntresvalles1')]</value>
      <webElementGuid>bf82ff0a-41c7-485b-b617-32c3e0e76762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/span/a</value>
      <webElementGuid>084d7347-2bcb-476b-94a5-913488ea6f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ntresvalles1' and (text() = '
        ntresvalles1
' or . = '
        ntresvalles1
')]</value>
      <webElementGuid>0086d321-2922-4eeb-aefe-81d9f2e76141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
