<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTesting</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8602b713-d4b3-4767-a281-dcd6226b968a</testSuiteGuid>
   <testCaseLink>
      <guid>1ee33172-cf15-41dd-b100-86bf036b9811</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC UDEMY/DataDrivenTesting</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>caf8886d-5ebb-4519-a718-dcf67006e67b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>caf8886d-5ebb-4519-a718-dcf67006e67b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>ba4f97cb-afd5-4632-a67b-30e1a37622ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>caf8886d-5ebb-4519-a718-dcf67006e67b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>ef099403-4d45-4a6f-81b6-3c39e68f5b71</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
