<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_home</name>
   <tag></tag>
   <elementGuidId>e97df4cf-116c-43a1-9429-eaee5b8a0bb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerPanel']/ul[2]/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.home > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;home&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b8466bf2-c2d9-43a0-b84b-100f85246b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.htm;jsessionid=CDB15A50EC1145FF766DBA4D9912FF00</value>
      <webElementGuid>306598e7-8549-49c0-8b81-51ee799824c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>home</value>
      <webElementGuid>47562f8f-dd8f-42d2-9161-4aeab2c034d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerPanel&quot;)/ul[@class=&quot;button&quot;]/li[@class=&quot;home&quot;]/a[1]</value>
      <webElementGuid>815774df-b769-4b89-ae7a-a17db9901c5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerPanel']/ul[2]/li/a</value>
      <webElementGuid>0f0223f0-3367-496d-804a-1315ddea896c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'home')]</value>
      <webElementGuid>929b902b-d2ba-42d5-8729-803bef1907bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Page'])[1]/following::a[1]</value>
      <webElementGuid>e4293b61-9d64-4373-88c6-fdf1c3118671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locations'])[1]/following::a[2]</value>
      <webElementGuid>2a4694d3-f83c-4a3d-8bcd-c1adc6e2b610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='about'])[1]/preceding::a[1]</value>
      <webElementGuid>d53e161e-7a64-4a9f-a01f-7fccf49705f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contact'])[1]/preceding::a[2]</value>
      <webElementGuid>5d681993-4d97-4696-ae9d-dd005292c23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='home']/parent::*</value>
      <webElementGuid>504c567b-a930-4f44-8897-37e45dc36c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'index.htm;jsessionid=CDB15A50EC1145FF766DBA4D9912FF00')])[2]</value>
      <webElementGuid>83fa92a0-ed36-4f37-bfcb-18cea38f483a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/a</value>
      <webElementGuid>bceede4f-0d91-42ff-8819-16363916ce29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.htm;jsessionid=CDB15A50EC1145FF766DBA4D9912FF00' and (text() = 'home' or . = 'home')]</value>
      <webElementGuid>b292c0e9-73a7-4714-9edf-daaa95f5601d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
