<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Solutions_logo</name>
   <tag></tag>
   <elementGuidId>a203ad0b-882e-4bc9-9a8f-613a30787133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topPanel']/a[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ParaBank&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2263847b-c26c-4d09-9b71-4531179acde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/logo.gif;jsessionid=CDB15A50EC1145FF766DBA4D9912FF00</value>
      <webElementGuid>c5e71267-4ac7-4531-baa5-fa6c5592e7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ParaBank</value>
      <webElementGuid>d873c48f-cae4-4a52-bf11-5bc89b4b4685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>136</value>
      <webElementGuid>301ead74-9d71-4c3d-a591-6f5e1f17ef85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>d575235c-42fa-402d-bc03-127bbd59f10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>11012a7a-155f-4055-a376-80e680d56f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>39266ce9-1722-4d7f-b3cc-d01c1fca54a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ParaBank</value>
      <webElementGuid>511c6a24-4ec3-4b73-b230-0a035c8c6aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topPanel&quot;)/a[2]/img[@class=&quot;logo&quot;]</value>
      <webElementGuid>d2cbb7a8-9cd0-436b-8cf1-8959c1f5bdce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topPanel']/a[2]/img</value>
      <webElementGuid>6301b604-4730-48e6-8fb5-e234fcaca62e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ParaBank']</value>
      <webElementGuid>f153826e-6b80-444f-a984-69658deccf4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>cb0411b4-8aa1-4d9b-886b-7797ed282d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/logo.gif;jsessionid=CDB15A50EC1145FF766DBA4D9912FF00' and @alt = 'ParaBank' and @title = 'ParaBank']</value>
      <webElementGuid>4b757f01-44db-49ff-b266-96464748e2eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
