<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_rrtyjujmhgfgde</name>
   <tag></tag>
   <elementGuidId>3d761ce9-5450-4f89-8918-136b510e2be9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='botstuff']/div/div[2]/div/p/span/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>4b4a126b-e846-4a11-9b4a-e6ef57eb44ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rrtyjujmhgfgde</value>
      <webElementGuid>7b1148f4-a1f0-434e-a04a-5e6c1d804e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;botstuff&quot;)/div[1]/div[@class=&quot;mnr-c&quot;]/div[@class=&quot;card-section&quot;]/p[1]/span[1]/em[1]</value>
      <webElementGuid>48ad92ff-bf01-4de6-b268-8297758d3d9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='botstuff']/div/div[2]/div/p/span/em</value>
      <webElementGuid>bc1a4354-665c-42df-81f5-3d285ac8da1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms'])[1]/following::em[1]</value>
      <webElementGuid>294d35d4-2888-4ffb-aceb-94b0fe87508d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/following::em[1]</value>
      <webElementGuid>cd327275-cdb5-4668-83ad-839eb8adada7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make sure that all words are spelled correctly.'])[1]/preceding::em[1]</value>
      <webElementGuid>5d6e006a-68df-4874-bc6e-485afb55531e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try different keywords.'])[1]/preceding::em[1]</value>
      <webElementGuid>946117ee-cbb9-4abd-aa17-85c6096b5dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>8ed7fa4b-c0cc-4859-9956-efa27e19eb3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'rrtyjujmhgfgde' or . = 'rrtyjujmhgfgde')]</value>
      <webElementGuid>1500a0a2-206a-4f0a-8eba-ce2663e3c309</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
