<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GitHub CLI_form-control input-monospa_e53e3d</name>
   <tag></tag>
   <elementGuidId>664dd318-b060-42b2-a894-93d5ece0621e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.input-monospace.input-sm.color-bg-subtle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='https://github.com/SauravMukherjee44/CodeIN-Community-Website.git']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;https://github.com/SauravMukherjee44/CodeIN-Community-Website.git&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00459027-5108-424d-9abb-31361546e07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29dc618e-37d5-4e9e-841c-a48c9175c461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-monospace input-sm color-bg-subtle</value>
      <webElementGuid>728e9b08-2f34-4ebb-ac53-7d6a43439f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autoselect</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>582cbed0-b65d-4157-9bd6-283145dda6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>https://github.com/SauravMukherjee44/CodeIN-Community-Website.git</value>
      <webElementGuid>19464f38-efa9-417f-bedf-ba33c63d1ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>https://github.com/SauravMukherjee44/CodeIN-Community-Website.git</value>
      <webElementGuid>3c8760a0-29fd-4c02-ace8-ed97e20ef8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b1a97798-56f8-4d3e-9acc-b8cdb221db6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__primerPortalRoot__&quot;)/div[1]/div[@class=&quot;Overlay__StyledOverlay-sc-51280t-0 iDsXZs&quot;]/div[1]/ul[@class=&quot;List__ListBox-sc-1x7olzq-0 bPkpYX react-overview-code-button-action-list&quot;]/div[1]/div[@class=&quot;Box-sc-g0xbh4-0 xRPxW&quot;]/div[@class=&quot;Box-sc-g0xbh4-0 cMYnca&quot;]/div[@class=&quot;Box-sc-g0xbh4-0 bPtETJ&quot;]/input[@class=&quot;form-control input-monospace input-sm color-bg-subtle&quot;]</value>
      <webElementGuid>ee0b62a1-907d-4c2e-850e-fb4b7fc27901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='https://github.com/SauravMukherjee44/CodeIN-Community-Website.git']</value>
      <webElementGuid>7bc2b93f-6594-4202-a49e-2664359f8a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__primerPortalRoot__']/div/div/div/ul/div/div/div[2]/div/input</value>
      <webElementGuid>8724fa0a-97cb-427a-9058-a98a4a1cab57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/div/div[2]/div/input</value>
      <webElementGuid>b2a843f1-8143-4f44-8630-e83d5aff540c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>fc33131f-c1df-49aa-a4dd-db69a23610e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
