<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Doctor-Portfolio</name>
   <tag></tag>
   <elementGuidId>d4544a52-1a01-4556-911c-7c9357fbc78a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div/ul/li[2]/div/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Doctor-Portfolio&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>42b5023c-3069-4a37-964c-f3d0b967c603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://github.com/jrohitofficial/Doctor-Portfolio</value>
      <webElementGuid>e6c02b9b-ad29-4286-afe6-d8557890b5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Doctor-Portfolio</value>
      <webElementGuid>20a85b5e-0fc0-44d3-8a02-6bbd44056ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;DefaultLayout_1jug6qr u-flex u-flexCol&quot;]/div[@class=&quot;u-flexGrow1&quot;]/div[@class=&quot;Container_16pg94n&quot;]/div[@class=&quot;Container_inner_w9z6jj-o_O-Container_padding_1cv73u5&quot;]/div[@class=&quot;Profile_container_9yvb3b&quot;]/div[@class=&quot;Profile_content_rci9mp Grid Grid--withGutter&quot;]/div[@class=&quot;Profile_repos_koa90h Grid-cell u-sm-size1of2&quot;]/ul[1]/li[@class=&quot;ItemList_item_dgdnyv&quot;]/div[1]/p[@class=&quot;Repo_name_y4kf6o u-flex u-flexAlignItemsBaseline&quot;]/a[1]</value>
      <webElementGuid>1cda69e4-6902-40a0-b25b-cf59f3b64733</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div/ul/li[2]/div/p/a</value>
      <webElementGuid>9f6e0b5e-d37a-4674-b368-297fb09c636d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Doctor-Portfolio')]</value>
      <webElementGuid>2b073c79-c065-4ecf-8708-740c2177756d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jrohitofficial'])[1]/following::a[1]</value>
      <webElementGuid>5eeb8a0b-56d4-4c48-a79d-cba7d91a3b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repositories'])[1]/following::a[2]</value>
      <webElementGuid>66e85052-48fe-4d88-bbd9-bb579f0c4ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='palmmind-task1_CRUD-LOGIN-SIGNUP'])[1]/preceding::a[1]</value>
      <webElementGuid>184b02bf-f62d-4249-b101-3b2827d19fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='palmmind-task4_-Simple-Http-request'])[1]/preceding::a[2]</value>
      <webElementGuid>37cccf5d-2db2-4b52-8024-ea6428672329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Doctor-Portfolio']/parent::*</value>
      <webElementGuid>a85d0172-eb27-494e-9159-e080febfa953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://github.com/jrohitofficial/Doctor-Portfolio')]</value>
      <webElementGuid>0089daab-b705-4bf8-afb8-b8696df2182f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/p/a</value>
      <webElementGuid>d2cb85ce-8316-4b14-b907-6fba0d9716af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://github.com/jrohitofficial/Doctor-Portfolio' and (text() = 'Doctor-Portfolio' or . = 'Doctor-Portfolio')]</value>
      <webElementGuid>fba63ff4-a4e1-4af1-b75e-2681d052f92b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
