<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_kritika-srivastava</name>
   <tag></tag>
   <elementGuidId>52090775-8a53-483d-b5d8-8e48a3861bba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/ul/li[3]/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;kritika-srivastava's avatar kritika-srivastava&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a430e97d-a453-4821-9dae-faeeb59fc011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>User_username_rnfkwd</value>
      <webElementGuid>72aeb8f1-0918-491c-ab25-9e12c19923f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>kritika-srivastava</value>
      <webElementGuid>714ee10f-0fe0-44c8-9b63-d21e9a0f31ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;DefaultLayout_1jug6qr u-flex u-flexCol&quot;]/div[@class=&quot;u-flexGrow1&quot;]/div[@class=&quot;Container_16pg94n&quot;]/div[@class=&quot;Container_inner_w9z6jj-o_O-Container_padding_1cv73u5&quot;]/div[@class=&quot;SearchResultsContainer_item_1mcype0&quot;]/ul[@class=&quot;SearchResults_1uxrx9c u-sm-flex u-sm-flexWrap&quot;]/li[@class=&quot;SearchResults_item_1mclqe7&quot;]/a[@class=&quot;User_abw475 u-flex&quot;]/p[@class=&quot;User_username_rnfkwd&quot;]</value>
      <webElementGuid>6a6d3396-0387-4eb0-9734-7c094e6f0e10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/ul/li[3]/a/p</value>
      <webElementGuid>1a8d1457-3f03-4c7c-8265-0340c0a83715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kritika'])[1]/following::p[3]</value>
      <webElementGuid>24c3d85b-5199-497d-960a-80cef3089237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::p[4]</value>
      <webElementGuid>aac56a08-7e17-4e4c-8783-558c9787b53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::p[40]</value>
      <webElementGuid>8a880889-660e-4aa3-a625-798d8447e962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='source on GitHub'])[1]/preceding::p[40]</value>
      <webElementGuid>00b1edf0-626c-4aa2-920c-baea991e85b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='kritika-srivastava']/parent::*</value>
      <webElementGuid>a9166f22-21f6-47ee-9ebd-6d46e5c7bd87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/p</value>
      <webElementGuid>d9f5aa7a-bb68-45bd-ba25-7894a266b377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'kritika-srivastava' or . = 'kritika-srivastava')]</value>
      <webElementGuid>e9717d49-9aa4-45e5-8283-cd2928e78e6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
