<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_external-snapshot-metadata</name>
   <tag></tag>
   <elementGuidId>d88f9fea-f6a7-4d1e-a5ea-2b6d9947d05e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div/ul/li[4]/div/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;external-snapshot-metadata&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1dacf86f-319e-43d3-9333-8d5c49c0094b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://github.com/PrasadG193/external-snapshot-metadata</value>
      <webElementGuid>c11d794b-aa2e-4f0b-885f-4de66c8ebf53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>external-snapshot-metadata</value>
      <webElementGuid>6484375e-00e7-40ac-86e4-ff7ab60e34d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;DefaultLayout_1jug6qr u-flex u-flexCol&quot;]/div[@class=&quot;u-flexGrow1&quot;]/div[@class=&quot;Container_16pg94n&quot;]/div[@class=&quot;Container_inner_w9z6jj-o_O-Container_padding_1cv73u5&quot;]/div[@class=&quot;Profile_container_9yvb3b&quot;]/div[@class=&quot;Profile_content_rci9mp Grid Grid--withGutter&quot;]/div[@class=&quot;Profile_repos_koa90h Grid-cell u-sm-size1of2&quot;]/ul[1]/li[@class=&quot;ItemList_item_dgdnyv&quot;]/div[1]/p[@class=&quot;Repo_name_y4kf6o u-flex u-flexAlignItemsBaseline&quot;]/a[1]</value>
      <webElementGuid>58140415-4c5f-465d-8fd6-232a8f2f841b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div/ul/li[4]/div/p/a</value>
      <webElementGuid>d2186bb5-ab53-4861-9592-71c9c88605cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'external-snapshot-metadata')])[2]</value>
      <webElementGuid>e9a88b1c-a302-4911-8aa4-acacd3566d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='k8s-cbt'])[1]/following::a[1]</value>
      <webElementGuid>ae8a32f8-df7b-4138-b344-f58232822668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(fork)'])[2]/following::a[2]</value>
      <webElementGuid>5703b2e7-a4d1-4b10-ae2e-3cf66a9568d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gener8-Llama2'])[1]/preceding::a[1]</value>
      <webElementGuid>ee3dee2c-4f38-4ec2-b014-34a3bc781a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kanister'])[1]/preceding::a[2]</value>
      <webElementGuid>2c7f69fc-763c-4006-9a4b-4e9b6c73bccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='external-snapshot-metadata']/parent::*</value>
      <webElementGuid>16b18b87-76d9-47e4-abe1-c8dc5d1993dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://github.com/PrasadG193/external-snapshot-metadata')]</value>
      <webElementGuid>4cf5f645-ec08-4db1-9f15-69e0356ee44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/p/a</value>
      <webElementGuid>1865c0f9-ac14-4923-86b3-c81a2077e608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://github.com/PrasadG193/external-snapshot-metadata' and (text() = 'external-snapshot-metadata' or . = 'external-snapshot-metadata')]</value>
      <webElementGuid>8ff99321-dd12-497d-b9e6-5ade776d86df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
