<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ground_up_basics_trust_ml</name>
   <tag></tag>
   <elementGuidId>8e774763-ea13-4859-9c8d-6f89df1e4797</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.Repo_name_y4kf6o.u-flex.u-flexAlignItemsBaseline > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div/ul/li/div/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ground_up_basics_trust_ml&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5fbb768a-d0ef-4e05-a8e0-90fdb2cd7286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://github.com/Kritikalcoder/ground_up_basics_trust_ml</value>
      <webElementGuid>a8421d04-6226-4ff1-9d6d-b1e4c789f4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ground_up_basics_trust_ml</value>
      <webElementGuid>3540f3b6-f7a6-4bff-ac6f-48fc087d019e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;DefaultLayout_1jug6qr u-flex u-flexCol&quot;]/div[@class=&quot;u-flexGrow1&quot;]/div[@class=&quot;Container_16pg94n&quot;]/div[@class=&quot;Container_inner_w9z6jj-o_O-Container_padding_1cv73u5&quot;]/div[@class=&quot;Profile_container_9yvb3b&quot;]/div[@class=&quot;Profile_content_rci9mp Grid Grid--withGutter&quot;]/div[@class=&quot;Profile_repos_koa90h Grid-cell u-sm-size1of2&quot;]/ul[1]/li[@class=&quot;ItemList_item_dgdnyv&quot;]/div[1]/p[@class=&quot;Repo_name_y4kf6o u-flex u-flexAlignItemsBaseline&quot;]/a[1]</value>
      <webElementGuid>ade825f4-1d32-42f5-8b73-8bdfa9106813</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div/ul/li/div/p/a</value>
      <webElementGuid>9443966d-c294-4370-a7d5-6de579a5f599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ground_up_basics_trust_ml')]</value>
      <webElementGuid>50785ec4-9e85-428e-83cb-32fbf3cb7ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repositories'])[1]/following::a[1]</value>
      <webElementGuid>c55bcfdf-d865-4254-9820-6bc01b6391e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kritipraks.com'])[1]/following::a[1]</value>
      <webElementGuid>0ace6c2b-1b06-4bf8-81c0-c7f576c656eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRIL'])[1]/preceding::a[1]</value>
      <webElementGuid>fe7bef04-e01b-417a-8c65-5d1c51ecd3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(fork)'])[1]/preceding::a[2]</value>
      <webElementGuid>280ddd14-f1ac-4cd3-b8ca-8811ed66ca77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ground_up_basics_trust_ml']/parent::*</value>
      <webElementGuid>175795dd-9ae4-40ba-86cd-eded48256f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://github.com/Kritikalcoder/ground_up_basics_trust_ml')]</value>
      <webElementGuid>a810fb08-fab3-4ce7-a0a6-30f7718f162d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/p/a</value>
      <webElementGuid>1b6c7114-99fe-4323-b3f3-fabae8faf395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://github.com/Kritikalcoder/ground_up_basics_trust_ml' and (text() = 'ground_up_basics_trust_ml' or . = 'ground_up_basics_trust_ml')]</value>
      <webElementGuid>6d5b9c9e-67ca-4a67-b3bf-4db7bef373a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
